name: Update Muni Data Cache

on:
  schedule:
    - cron: '*/5 12-23 * * 1-5'  # Every 5 minutes, 5am-4pm PT (12-23 UTC) on weekdays
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'  # Use the gh-pages branch
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Fetch latest Muni data
        run: |
          mkdir -p data
          
          # Fetch data for N-Judah stop (14448)
          curl -s "https://api.511.org/transit/StopMonitoring?api_key=${{ secrets.API_KEY }}&agency=SF&stopCode=14448&format=json" > data/stop-14448.json || echo "Failed to fetch N-Judah data"
          
          # Fetch data for J-Church stop (17073)
          curl -s "https://api.511.org/transit/StopMonitoring?api_key=${{ secrets.API_KEY }}&agency=SF&stopCode=17073&format=json" > data/stop-17073.json || echo "Failed to fetch J-Church data"
          
          # Create metadata file with timestamp
          echo "{\"lastUpdated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > data/metadata.json
      
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/
          git commit -m "Update Muni data cache" || echo "No changes to commit"
          git push || echo "Failed to push changes"
